### ISSUE TITLE
hutool-core版本太低导致NoSuchMethodError, trace=java.lang.NoSuchMethodError: 'boolean cn.hutool.core.bean.BeanUtil.isReadableBean(java.lang.Class)'

### ISSUE THREAD

**Issue by alterhu2020** [justauth/justauth-spring-boot-starter#8]
当前最新版中引用的 hutool-core版本是5.1.0,因为版本太低在使用方法: `JSONUtil.toJsonStr(obj)`的时候会报如下错误：
```
eption=java.lang.NoSuchMethodError, trace=java.lang.NoSuchMethodError: 'boolean cn.hutool.core.bean.BeanUtil.isReadableBean(java.lang.Class)'
	at cn.hutool.json.JSONObject.init(JSONObject.java:690)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:202)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:225)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:196)
	at cn.hutool.json.JSONUtil.toJsonStr(JSONUtil.java:373)

```

建议更新对应hutool-core版本，否则在使用以上方法时候会报错。

**Comment by xkcoding** [comment]
近期会发布新版，已更新到 `hutool-core` 的最新版本，敬请期待
